### ISSUE TITLE
Make volunteering/ non profit sign up one touch

### ISSUE THREAD

**Issue by rapidexpert** [womenhackfornonprofits/whfnp#45]
Adding a Signup button to the home page next to the volunteer with us would allow people or partners who want to sign up ( eg friend/partner referral, engaged through social media) do this without reading further information.

**Comment by EChesters** [comment]
Doing it this way means we're expecting users, to know everything they need to know about signing up, and taking them from home page to full commitment in one click. 
After speaking to volunteers for personas, every single one of them had questions. Using the one click approach is used for scenarios like impulse buying.. not signing up and volunteering. 

People are volunteering because they already have tie to spare. Allowing them to read and click through our website to answer the questions they do have will not hinder the UX of this website. The one-click approach will.

**Comment by tanyapowell** [comment]
@rapidexpert I'm closing this issue as @EChesters' research showed it would be more harmful than useful
