### ISSUE TITLE
Volunteer form fields - additional useful? Fields

### ISSUE THREAD

**Issue by rapidexpert** [womenhackfornonprofits/whfnp#46]
## Making the volunteer form a single source of entry
- [ ] Github username | _allow invitation to Organisation Github_
- [ ] Join our messaging app on Slack | _allows us to send invitation to interested users_
- [ ] Join our group on Meetup | _allows us to send invitation to interested users_
- [ ] Join our group on Facebook | _helps us to invite users to like our page_
- [ ] Join our mailing list for Newsletter updates  | _helps volunteers to sign up in one place_
- [ ] Source information | _helps us to track which outlet eg social media / user / org, possibly 2 fields   source type, source url /email)_

**Comment by tanyapowell** [comment]
Whilst some of these extra questions are valid, an overly long form to fill in when signing up for anything is off putting. 

Source information has already been implemented.

@womenhackfornonprofits/whfnp can you think of a compromise between what we currently have and these suggestions?

**Comment by EChesters** [comment]
The information that they give us here will probably not be used. We need to make onboarding as easy as possible. We do not need their Facebook. That's something that's usually not used professionally. 

I don't understand what source information is, and I've never seen that on a form. 

Forcing someone to sign up to our newsletter is needy, and while it might get us the numbers of subscribers we want, we can't tell that it's for the right reasons and that people are actually wanting to sign up. I suggest we do not include that on the form. 

We need email to invite people to slack and then include most of this information through onboarding and talking to people. People like accountants and marketing who are in the group don't have Github for example. This will be very off putting.

**Comment by tanyapowell** [comment]
Source information:
![image](https://cloud.githubusercontent.com/assets/11095605/15402631/2453ed52-1ded-11e6-9ddb-dbd40f9c60d9.png)

Signing up for the newsletter whilst signing up as a volunteer is a good idea. It doesn't have to be a required field, but is a good option. The same with GitHub. Having them as optional fields will help the onboarding process if we already have that information and don't need to pester people for it after, but if they are optional volunteers don't feel obliged to fill that part in.

**Comment by EChesters** [comment]
Okay so we have two goals here which are somewhat conflicting each other. 

1) We want people to sign up
- A long form where we require absolutely everything because we want the information or because we want to include people in everything from the get go is going to put people off. A lot of people at meetup have signed up but have no idea what they've signed up to. If we're not explaining that well we do need to address this, but also asking for newsletter sign up from the get go is off putting and needy.
  **Keep the form to the bare minimum**

2) We want people to sign up to the newsletter
- We could offer this as part of onboarding - not as part of the sign up process. So after the form has been submitted, tell them thank you, and offer the ways of getting involved right there and then. 'Sign up to our newsletter for monthly updates on all the projects and exciting things that we're doing!" "Why not follow us on Twitter, so we can follow you back?" Something along those lines, not exactly that. 
  **Make it in the user's interest after they've committed to sign up to the newsletter**

Thoughts on this approach? We can keep an eye on the analytics for this if were unsure.

**Comment by lili2311** [comment]
Newsletter signup is already offered as part of onboarding when they receive a welcome email and on the pages on the website if anyone fancies signing up.

Everything mentioned in above ticket is sent to the newly signed up users to join as part of the welcome email and they choose to go and signup for one or all. This ticket can be closed in my opinion since we already provide all this but as part of user onboarding after they filled out the form.

**Comment by EChesters** [comment]
For forms in general, the sign up one is too long and needs to be reconsidered. But I think there's another ticket for this already.

**Comment by lili2311** [comment]
Closing issue since it is all covered in Onboarding email.
