### ISSUE TITLE
Extract as much as possible into partials

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#90]
There's a few things that are yet to be extracted into partials. 

From a first glance the `head` section, `analytics` script, `navbar` needs redoing to be in one file only, and logo needs to be moved inside the navbar.

Feel free to add anything I've missed!

**Comment by lili2311** [comment]
Yes indeed I assumed whoever is converting each file can add whatever seems necessary into partials.

**Comment by EChesters** [comment]
Oke dokes! There's just a lot that needs to be done for `index.html` which doesn't have an issue raised for it.

**Comment by lili2311** [comment]
Yep I didn't want to do it all and leave nothing for anyone else :D I can finish index.html if no one is keen

**Comment by EChesters** [comment]
Nah, it's okay. I'm happy to pick this up and go through the list of what needs doing. If you think I've missed something please add it.

**Comment by tanyapowell** [comment]
@lili2311 is the logo outside of the navbars because there are two navbars (desktop and mobile)? And we'd have to add it to both navbars if we were to place it inside?

**Comment by lili2311** [comment]
hey! The logo is not semantically a menu and should not be in the nav bar. Since we do not want it to behave like the navbar menu item or be the same height. And especially we do not want to have it twice and get the browser to download it twice.

Having the logon in the navbar would make it harder to style and especially o mobile where only the menu items are hidden behind the hamburger.
